# Generated by Django 4.1.5 on 2023-11-02 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_alter_recipeingredientimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeingredientimage',
            name='extracted',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
