# Generated by Django 4.1.5 on 2023-10-17 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artcles', '0003_article_publish'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='publish',
        ),
        migrations.AddField(
            model_name='article',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
